/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWalletRouteImport } from './routes/dashboard/wallet'
import { Route as DashboardUploadRouteImport } from './routes/dashboard/upload'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSchemasRouteImport } from './routes/dashboard/schemas'
import { Route as DashboardExecutionsRouteImport } from './routes/dashboard/executions'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardExecutionsIndexRouteImport } from './routes/dashboard/executions.index'
import { Route as DashboardExecutionsIdRouteImport } from './routes/dashboard/executions.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchemasRoute = DashboardSchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExecutionsRoute = DashboardExecutionsRouteImport.update({
  id: '/executions',
  path: '/executions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExecutionsIndexRoute =
  DashboardExecutionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardExecutionsRoute,
  } as any)
const DashboardExecutionsIdRoute = DashboardExecutionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardExecutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/executions': typeof DashboardExecutionsRouteWithChildren
  '/dashboard/schemas': typeof DashboardSchemasRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/executions/$id': typeof DashboardExecutionsIdRoute
  '/dashboard/executions/': typeof DashboardExecutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/schemas': typeof DashboardSchemasRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/executions/$id': typeof DashboardExecutionsIdRoute
  '/dashboard/executions': typeof DashboardExecutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/executions': typeof DashboardExecutionsRouteWithChildren
  '/dashboard/schemas': typeof DashboardSchemasRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/executions/$id': typeof DashboardExecutionsIdRoute
  '/dashboard/executions/': typeof DashboardExecutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/executions'
    | '/dashboard/schemas'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/wallet'
    | '/dashboard/'
    | '/dashboard/executions/$id'
    | '/dashboard/executions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/schemas'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/wallet'
    | '/dashboard'
    | '/dashboard/executions/$id'
    | '/dashboard/executions'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/executions'
    | '/dashboard/schemas'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/wallet'
    | '/dashboard/'
    | '/dashboard/executions/$id'
    | '/dashboard/executions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schemas': {
      id: '/dashboard/schemas'
      path: '/schemas'
      fullPath: '/dashboard/schemas'
      preLoaderRoute: typeof DashboardSchemasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/executions': {
      id: '/dashboard/executions'
      path: '/executions'
      fullPath: '/dashboard/executions'
      preLoaderRoute: typeof DashboardExecutionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/executions/': {
      id: '/dashboard/executions/'
      path: '/'
      fullPath: '/dashboard/executions/'
      preLoaderRoute: typeof DashboardExecutionsIndexRouteImport
      parentRoute: typeof DashboardExecutionsRoute
    }
    '/dashboard/executions/$id': {
      id: '/dashboard/executions/$id'
      path: '/$id'
      fullPath: '/dashboard/executions/$id'
      preLoaderRoute: typeof DashboardExecutionsIdRouteImport
      parentRoute: typeof DashboardExecutionsRoute
    }
  }
}

interface DashboardExecutionsRouteChildren {
  DashboardExecutionsIdRoute: typeof DashboardExecutionsIdRoute
  DashboardExecutionsIndexRoute: typeof DashboardExecutionsIndexRoute
}

const DashboardExecutionsRouteChildren: DashboardExecutionsRouteChildren = {
  DashboardExecutionsIdRoute: DashboardExecutionsIdRoute,
  DashboardExecutionsIndexRoute: DashboardExecutionsIndexRoute,
}

const DashboardExecutionsRouteWithChildren =
  DashboardExecutionsRoute._addFileChildren(DashboardExecutionsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardExecutionsRoute: typeof DashboardExecutionsRouteWithChildren
  DashboardSchemasRoute: typeof DashboardSchemasRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardExecutionsRoute: DashboardExecutionsRouteWithChildren,
  DashboardSchemasRoute: DashboardSchemasRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
